# Generated by Django 5.2.3 on 2025-07-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='front_page',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
